#!/bin/bash
set -e

BASE="paper_results/2026"

echo "======================================"
echo " FIXING PAPER ARTIFACT COMPLETENESS"
echo "======================================"
echo

# -------------------------
# Fix root README citation
# -------------------------
if ! grep -qi "## Citation" README.md; then
  echo "Adding CITATION section to README.md"
  cat >> README.md << 'CITE'

## Citation

If you use this repository or its artifacts in academic work, please cite:

@misc{abdullah2026aegisgrid,
  title={Aegis-Grid: Deterministic Multi-Layer Cyber-Physical Defense Architecture},
  author={Abdullah, Burhan},
  year={2026},
  howpublished={GitHub},
  url={https://github.com/BurhanAbdullah/Aegis-Grid}
}

CITE
else
  echo "CITATION section already present"
fi

# -------------------------
# Per-model fixes
# -------------------------
for d in "$BASE"/*; do
  [ -d "$d" ] || continue
  MODEL=$(basename "$d")

  echo
  echo "Processing model: $MODEL"

  DOC="$d/README.md"
  HASH="$d/REPRODUCIBILITY.txt"

  # -------------------------
  # Add model README
  # -------------------------
  if [ ! -f "$DOC" ]; then
    echo "Creating documentation for $MODEL"
    cat > "$DOC" << DOCFILE
# $MODEL — Paper Artifact

## Description
This directory contains tag-native, deterministic outputs for the Aegis-Grid $MODEL model.

## Contents
- CSV files: Raw model measurements
- PNG files: Figures generated directly from model execution
- REPRODUCIBILITY.txt: SHA256 hashes for audit and verification

## Reproducibility
These results were generated by running the model directly from its Git tag.

## Security Architecture (7 Layers)
1. Identity & Authentication
2. Cryptographic Transport
3. Fragmentation & Obfuscation
4. Behavioral Monitoring
5. Adaptive Control
6. Fail-Secure Enforcement
7. Cyber-Physical Safety Gate
DOCFILE
  else
    echo "Documentation exists"
  fi

  # -------------------------
  # Generate reproducibility file
  # -------------------------
  echo "Generating reproducibility hashes"
  find "$d" -type f ! -name "REPRODUCIBILITY.txt" -exec sha256sum {} \; > "$HASH"

  # -------------------------
  # Check PNG existence
  # -------------------------
  if ! ls "$d"/*.png >/dev/null 2>&1; then
    echo "⚠️ WARNING: No PNG figures found in $MODEL"
  else
    echo "PNG figures present"
  fi

done

echo
echo "======================================"
echo " PAPER ARTIFACT FIX COMPLETE"
echo "======================================"
